export interface FlightData {
    date: string,
    status: string,
    departureAirport: string,
    departureTimezone: string,
    departureIata: string,
    departureIcao: string,
    departureTerminal: string | number,
    departureGate: string,
    delay: number,
    scheduledDeparture: string,
    estimedDeparture: string,
    actualDeparture: string,
    departureEstimatedRunway: string,
    departureActualRunway: string,
    arrivalAirport: string,
    arrivalTimezone: string,
    arrivalIata: string,
    arrivalIcao: string,
    arrivalTerminal: string | number,
    arrivalGate: string,
    arrivalBaggage: string,
    arrivalDelay: number,
    scheduledArrival: string,
    estimedArrival: string,
    actualArrival: string | null,
    arrivalEstimatedRunway: string | null,
    arrivalActualRunway: string | null,
    airlineName: string,
    airlineIata: string,
    airlineIcao: string,
    flightNumber: string,
    flightIata: string,
    flightIcao: string,
    flightCodeshared: string | null,
    aircraftRegistration: string,
    aircraftIata: string,
    aircraftIcao: string,
    aircraftIcao24: string,
    lastUpdated: string,
    currentAltitude: number,
    currentLatitude: number,
    currentLongitude: number,
    currentHeading: number,
    currentHorizontalSpeed: number,
    currentVerticalSpeed: number,
    isOnGround: boolean
}